[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true


fs_permissions = [{ access = "read", path = "./airdrop-data" }]

remappings = [
    'murky/=lib/murky/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'foundry-devops/=lib/foundry-devops/',
    'forge-std/=lib/forge-std/src/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
